var classes = [
  {NAME:"College Bound Chemistry",DAY:"monday",MIN_AGE:14,MAX_AGE:18, TEACHER:"Dr. Thai", ROOM:4,TYPE:"default", START_TIME:"8:30", END_TIME:"10:30"},
  {NAME:"Elementary Mandarin",DAY:"monday",MIN_AGE:6,MAX_AGE:10, TEACHER:"Chang", ROOM:5,TYPE:"default", START_TIME:"8:00", END_TIME:"9:30"},
  {NAME:"Drawing Plus ",DAY:"monday",MIN_AGE:13,MAX_AGE:19, TEACHER:"Boone", ROOM:1,TYPE:"default", START_TIME:"9", END_TIME:"9:50"},
  {NAME:"Happy Feet",DAY:"monday",MIN_AGE:4,MAX_AGE:6, TEACHER:"Harnsberger", ROOM:9,TYPE:"default", START_TIME:"9:15", END_TIME:"10"},
  {NAME:"MS Mandarin",DAY:"monday",MIN_AGE:10,MAX_AGE:13, TEACHER:"Chang ", ROOM:5,TYPE:"default", START_TIME:"9:30", END_TIME:"11"},
  {NAME:"Stories of the US (History Alive)",DAY:"monday",MIN_AGE:8,MAX_AGE:12, TEACHER:"Giordano", ROOM:6,TYPE:"default", START_TIME:"9:30", END_TIME:"11"},
  {NAME:"ARTcetera",DAY:"monday",MIN_AGE:5,MAX_AGE:8, TEACHER:"Boone", ROOM:1,TYPE:"default", START_TIME:"10", END_TIME:"10:50"},
  {NAME:"ASL Preschool",DAY:"monday",MIN_AGE:3,MAX_AGE:6, TEACHER:"Anderegg", ROOM:8,TYPE:"default", START_TIME:"10", END_TIME:"10:45"},
  {NAME:"Beginning Hip Hop",DAY:"monday",MIN_AGE:6,MAX_AGE:10, TEACHER:"Harnsberger", ROOM:9,TYPE:"default", START_TIME:"10", END_TIME:"10:45"},
  {NAME:"Advanced Orchestra",DAY:"monday",MIN_AGE:-1,MAX_AGE:-1, TEACHER:"D. Rife", ROOM:3,TYPE:"default", START_TIME:"10:30", END_TIME:"12"},
  {NAME:"ARTcetera",DAY:"monday",MIN_AGE:10,MAX_AGE:12, TEACHER:"Boone ", ROOM:1,TYPE:"default", START_TIME:"11", END_TIME:"11:50"},
  {NAME:"HS Mandarin 1",DAY:"monday",MIN_AGE:14,MAX_AGE:18, TEACHER:"Chang", ROOM:5,TYPE:"default", START_TIME:"11", END_TIME:"12:30"},
  {NAME:"Stretch/ Conditioning",DAY:"monday",MIN_AGE:8,MAX_AGE:19, TEACHER:"Fisher", ROOM:9,TYPE:"default", START_TIME:"11:15", END_TIME:"12:00"},
  {NAME:"Advanced Curiosity Club",DAY:"monday",MIN_AGE:8,MAX_AGE:12, TEACHER:"Giordano", ROOM:6,TYPE:"default", START_TIME:"11:30", END_TIME:"1"},
  {NAME:"Classical Guitar  ",DAY:"monday",MIN_AGE:10,MAX_AGE:19, TEACHER:" L. Dircks   ", ROOM:1,TYPE:"default", START_TIME:"12", END_TIME:"1"},
  {NAME:"Instrument Ensemble",DAY:"monday",MIN_AGE:6,MAX_AGE:11, TEACHER:"Barrera", ROOM:3,TYPE:"default", START_TIME:"12", END_TIME:"1"},
  {NAME:"Intermediate Acro - non-performance",DAY:"monday",MIN_AGE:8,MAX_AGE:19, TEACHER:"Fisher", ROOM:9,TYPE:"default", START_TIME:"12", END_TIME:"1"},
  {NAME:"College Bound Chemistry",DAY:"monday",MIN_AGE:14,MAX_AGE:18, TEACHER:"Dr. Thai", ROOM:4,TYPE:"default", START_TIME:"12:30", END_TIME:"2:30"},
  {NAME:"Advanced Mandarin",DAY:"monday",MIN_AGE:14,MAX_AGE:18, TEACHER:"Chang", ROOM:5,TYPE:"default", START_TIME:"12:30", END_TIME:"2"},
  {NAME:"Beginning Violin",DAY:"monday",MIN_AGE:5,MAX_AGE:8, TEACHER:"Harpainter", ROOM:3,TYPE:"default", START_TIME:"1", END_TIME:"2"},
  {NAME:"Chess Club",DAY:"monday",MIN_AGE:7,MAX_AGE:19, TEACHER:"Cooke", ROOM:8,TYPE:"default", START_TIME:"1", END_TIME:"2:30"},
  {NAME:"Leaps...Turns... Creating Choreography Intermediate",DAY:"monday",MIN_AGE:8,MAX_AGE:19, TEACHER:"Fisher", ROOM:9,TYPE:"default", START_TIME:"1", END_TIME:"2"},
  {NAME:"Curiosity Club",DAY:"monday",MIN_AGE:6,MAX_AGE:8, TEACHER:"Giordano", ROOM:6,TYPE:"default", START_TIME:"1:30", END_TIME:"2:30"},
  {NAME:"Fraction Action",DAY:"monday",MIN_AGE:10,MAX_AGE:12, TEACHER:"Kugler", ROOM:1,TYPE:"default", START_TIME:"2", END_TIME:"3"},
  {NAME:"Advanced Chorale",DAY:"monday",MIN_AGE:10,MAX_AGE:19, TEACHER:"Barrera", ROOM:3,TYPE:"default", START_TIME:"2", END_TIME:"3"},
  {NAME:"Ballet II",DAY:"monday",MIN_AGE:10,MAX_AGE:19, TEACHER:" Harnsberger", ROOM:9,TYPE:"default", START_TIME:"2", END_TIME:"3"},
  {NAME:"Computer Science Fundamentals",DAY:"monday",MIN_AGE:4,MAX_AGE:11, TEACHER:"Elkins", ROOM:2,TYPE:"default", START_TIME:"2:30", END_TIME:"3:30"},
  {NAME:"True-to-Life Drawing",DAY:"monday",MIN_AGE:11,MAX_AGE:18, TEACHER:"Kugler", ROOM:1,TYPE:"default", START_TIME:"3", END_TIME:"4"},
  {NAME:"Rock Band 1",DAY:"monday",MIN_AGE:12,MAX_AGE:19, TEACHER:" L. Dircks   ", ROOM:3,TYPE:"default", START_TIME:"3", END_TIME:"4"},
  {NAME:"AP Music Theory ",DAY:"monday",MIN_AGE:14,MAX_AGE:18, TEACHER:" Barrera ", ROOM:5,TYPE:"default", START_TIME:"3", END_TIME:"4"},
  {NAME:"Beginning Contemporary / Lyrical Jazz",DAY:"monday",MIN_AGE:8,MAX_AGE:13, TEACHER:"B. Giordano", ROOM:9,TYPE:"default", START_TIME:"3", END_TIME:"4"},
  {NAME:"Foundations in Personal Finance with Dave Ramsey",DAY:"monday",MIN_AGE:14,MAX_AGE:18, TEACHER:"Elkins", ROOM:2,TYPE:"default", START_TIME:"3:30", END_TIME:"5"},
  {NAME:"Rock Band 2",DAY:"monday",MIN_AGE:12,MAX_AGE:19, TEACHER:" L. Dircks   ", ROOM:3,TYPE:"default", START_TIME:"4", END_TIME:"5"},
  {NAME:"Gymnastics",DAY:"monday",MIN_AGE:8,MAX_AGE:12, TEACHER:"Kugler", ROOM:9,TYPE:"default", START_TIME:"4", END_TIME:"5"},
  {NAME:"College Bound Physics",DAY:"tuesday",MIN_AGE:14,MAX_AGE:18, TEACHER:"Dr. Thai", ROOM:4,TYPE:"default", START_TIME:"8:30", END_TIME:"10:30"},
  {NAME:"Intro to Marine Biology",DAY:"tuesday",MIN_AGE:12,MAX_AGE:14, TEACHER:"N. Traicoff", ROOM:6,TYPE:"default", START_TIME:"8:30", END_TIME:"10"},
  {NAME:"Art a la Carte",DAY:"tuesday",MIN_AGE:9,MAX_AGE:12, TEACHER:"Sewell", ROOM:1,TYPE:"default", START_TIME:"9", END_TIME:"9:50"},
  {NAME:"Intro Math Mania",DAY:"tuesday",MIN_AGE:4,MAX_AGE:6, TEACHER:"Kugler", ROOM:2,TYPE:"default", START_TIME:"9", END_TIME:"10"},
  {NAME:"Food Masters",DAY:"tuesday",MIN_AGE:8,MAX_AGE:11, TEACHER:"Jenkins ", ROOM:5,TYPE:"default", START_TIME:"9", END_TIME:"10"},
  {NAME:"American Sign Language 1",DAY:"tuesday",MIN_AGE:14,MAX_AGE:18, TEACHER:"A. Smith", ROOM:8,TYPE:"default", START_TIME:"9", END_TIME:"10:30"},
  {NAME:"Intermediate Acro - Performance",DAY:"tuesday",MIN_AGE:7,MAX_AGE:19, TEACHER:"Fisher", ROOM:9,TYPE:"default", START_TIME:"9", END_TIME:"10"},
  {NAME:"MS Writing & Book Club",DAY:"tuesday",MIN_AGE:11,MAX_AGE:13, TEACHER:"Sewell", ROOM:1,TYPE:"default", START_TIME:"10", END_TIME:"11:15"},
  {NAME:"Rhythmic Gymnastics Level 2",DAY:"tuesday",MIN_AGE:10,MAX_AGE:19, TEACHER:"Fisher ", ROOM:9,TYPE:"default", START_TIME:"10", END_TIME:"11"},
  {NAME:"Road Trip Oceania / Antarctica",DAY:"tuesday",MIN_AGE:7,MAX_AGE:11, TEACHER:"Jenkins", ROOM:5,TYPE:"default", START_TIME:"10:15", END_TIME:"11:15"},
  {NAME:"Curiosity Club",DAY:"tuesday",MIN_AGE:4,MAX_AGE:6, TEACHER:"Giordano", ROOM:6,TYPE:"default", START_TIME:"10:15", END_TIME:"11:15"},
  {NAME:"Second Year Violin",DAY:"tuesday",MIN_AGE:5,MAX_AGE:19, TEACHER:"Harpainter", ROOM:3,TYPE:"default", START_TIME:"11", END_TIME:"12"},
  {NAME:"Honors Psychology from a Biblical Perspective",DAY:"tuesday",MIN_AGE:14,MAX_AGE:18, TEACHER:"Kirschner", ROOM:8,TYPE:"default", START_TIME:"11", END_TIME:"12:30"},
  {NAME:"Tap 4",DAY:"tuesday",MIN_AGE:12,MAX_AGE:19, TEACHER:"Fisher", ROOM:9,TYPE:"default", START_TIME:"11", END_TIME:"12"},
  {NAME:"Art a la Carte",DAY:"tuesday",MIN_AGE:4,MAX_AGE:7, TEACHER:"Sewell", ROOM:1,TYPE:"default", START_TIME:"11:15", END_TIME:"12:15"},
  {NAME:"MS/HS Engineering & Architecture (Castles and Coasters)",DAY:"tuesday",MIN_AGE:11,MAX_AGE:16, TEACHER:"Giordano", ROOM:6,TYPE:"default", START_TIME:"11:30", END_TIME:"1"},
  {NAME:"Chamber Orchestra",DAY:"tuesday",MIN_AGE:8,MAX_AGE:19, TEACHER:"Harpainter", ROOM:3,TYPE:"default", START_TIME:"12", END_TIME:"1"},
  {NAME:"Tap 1",DAY:"tuesday",MIN_AGE:11,MAX_AGE:19, TEACHER:"Fisher", ROOM:9,TYPE:"default", START_TIME:"12", END_TIME:"1"},
  {NAME:"Advanced Chemistry",DAY:"tuesday",MIN_AGE:14,MAX_AGE:18, TEACHER:"Dr. Thai", ROOM:4,TYPE:"default", START_TIME:"12:30", END_TIME:"3"},
  {NAME:"Elementary STEAM",DAY:"tuesday",MIN_AGE:7,MAX_AGE:11, TEACHER:"Jenkins", ROOM:5,TYPE:"default", START_TIME:"12:30", END_TIME:"1:30"},
  {NAME:"Ballet II/III w/ Beginning Pointe",DAY:"tuesday",MIN_AGE:12,MAX_AGE:19, TEACHER:"Harnsberger", ROOM:9,TYPE:"default", START_TIME:"1:15", END_TIME:"2:30"},
  {NAME:"History Alive! (WWI & WWII)",DAY:"tuesday",MIN_AGE:11,MAX_AGE:18, TEACHER:"Giordano ", ROOM:6,TYPE:"default", START_TIME:"2:30", END_TIME:"4"},
  {NAME:"Anatomy Book Club",DAY:"tuesday",MIN_AGE:7,MAX_AGE:10, TEACHER:" Jenkins", ROOM:5,TYPE:"default", START_TIME:"1:45", END_TIME:"2:45"},
  {NAME:"Ballet III with Pointe",DAY:"tuesday",MIN_AGE:12,MAX_AGE:19, TEACHER:"Harnsberger ", ROOM:9,TYPE:"default", START_TIME:"2:30", END_TIME:"4"},
  {NAME:"Journalism",DAY:"tuesday",MIN_AGE:7,MAX_AGE:18, TEACHER:"Lusteck", ROOM:2,TYPE:"default", START_TIME:"3", END_TIME:"4:30"},
  {NAME:"Math Mania Level B",DAY:"tuesday",MIN_AGE:7,MAX_AGE:8, TEACHER:"Jenkins", ROOM:5,TYPE:"default", START_TIME:"3", END_TIME:"4"},
  {NAME:"Martial Arts",DAY:"tuesday",MIN_AGE:5,MAX_AGE:8, TEACHER:"Fairweather", ROOM:8,TYPE:"default", START_TIME:"3:15", END_TIME:"4:05"},
  {NAME:"Ballet Folklorico Intermediate",DAY:"tuesday",MIN_AGE:10,MAX_AGE:19, TEACHER:" Zapata", ROOM:9,TYPE:"default", START_TIME:"4", END_TIME:"5"},
  {NAME:"Martial Arts",DAY:"tuesday",MIN_AGE:9,MAX_AGE:19, TEACHER:"Fairweather", ROOM:8,TYPE:"default", START_TIME:"4:15", END_TIME:"5:15"},
  {NAME:"Fiddle Jam Session",DAY:"tuesday",MIN_AGE:10,MAX_AGE:19, TEACHER:"Harpainter", ROOM:3,TYPE:"default", START_TIME:"5", END_TIME:"6"},
  {NAME:"Jazz Funk 3/4",DAY:"tuesday",MIN_AGE:8,MAX_AGE:19, TEACHER:" Harnsberger", ROOM:9,TYPE:"default", START_TIME:"5", END_TIME:"6"},
  {NAME:"Geometry",DAY:"wednesday",MIN_AGE:14,MAX_AGE:18, TEACHER:"Tucker ", ROOM:4,TYPE:"default", START_TIME:"8:30", END_TIME:"10"},
  {NAME:"ARTcetera",DAY:"wednesday",MIN_AGE:8,MAX_AGE:10, TEACHER:"Boone ", ROOM:1,TYPE:"default", START_TIME:"9", END_TIME:"9:50"},
  {NAME:"Characters in Crisis - Literature",DAY:"wednesday",MIN_AGE:14,MAX_AGE:18, TEACHER:"Lusteck", ROOM:5,TYPE:"default", START_TIME:"9", END_TIME:"10:30"},
  {NAME:"Caterpillar Clubhouse Preschool",DAY:"wednesday",MIN_AGE:3,MAX_AGE:4, TEACHER:"Gomes", ROOM:6,TYPE:"default", START_TIME:"9", END_TIME:"11"},
  {NAME:"Irish Step Dance (Advanced)",DAY:"wednesday",MIN_AGE:8,MAX_AGE:19, TEACHER:"McGrory", ROOM:9,TYPE:"default", START_TIME:"9", END_TIME:"10"},
  {NAME:"Drawing Plus! 2.0",DAY:"wednesday",MIN_AGE:13,MAX_AGE:19, TEACHER:"Boone", ROOM:1,TYPE:"default", START_TIME:"10", END_TIME:"10:50"},
  {NAME:"Typing Club",DAY:"wednesday",MIN_AGE:7,MAX_AGE:19, TEACHER:"Jenkins", ROOM:2,TYPE:"default", START_TIME:"10", END_TIME:"11"},
  {NAME:"Beginning Strings Ensemble",DAY:"wednesday",MIN_AGE:10,MAX_AGE:19, TEACHER:"Harpainter", ROOM:3,TYPE:"default", START_TIME:"10", END_TIME:"11"},
  {NAME:"Math Office Hours for Pre-Algebra/ Algebra 1/ Algebra 2/  Pre-Calculus/ & Trigonometry",DAY:"wednesday",MIN_AGE:14,MAX_AGE:18, TEACHER:"Tucker", ROOM:4,TYPE:"default", START_TIME:"10", END_TIME:"3"},
  {NAME:"Physical Science",DAY:"wednesday",MIN_AGE:8,MAX_AGE:9, TEACHER:"Elkins", ROOM:8,TYPE:"default", START_TIME:"10", END_TIME:"11:30"},
  {NAME:"Irish Step Dance (Beginning)",DAY:"wednesday",MIN_AGE:7,MAX_AGE:11, TEACHER:"McGrory", ROOM:9,TYPE:"default", START_TIME:"10", END_TIME:"11"},
  {NAME:"Language Arts Upper Elementary",DAY:"wednesday",MIN_AGE:10,MAX_AGE:12, TEACHER:"Lusteck", ROOM:5,TYPE:"default", START_TIME:"10:45", END_TIME:"11:45"},
  {NAME:"ARTcetera",DAY:"wednesday",MIN_AGE:-1,MAX_AGE:-1, TEACHER:"Boone ", ROOM:1,TYPE:"default", START_TIME:"11", END_TIME:"11:50"},
  {NAME:"Beginning Band",DAY:"wednesday",MIN_AGE:10,MAX_AGE:19, TEACHER:"Barrera", ROOM:3,TYPE:"default", START_TIME:"11", END_TIME:"12"},
  {NAME:"Praise / Contemporary II",DAY:"wednesday",MIN_AGE:9,MAX_AGE:19, TEACHER:"Fisher", ROOM:9,TYPE:"default", START_TIME:"11", END_TIME:"12"},
  {NAME:"Math Mania Level C",DAY:"wednesday",MIN_AGE:9,MAX_AGE:10, TEACHER:" Jenkins ", ROOM:2,TYPE:"default", START_TIME:"11:15", END_TIME:"12:15"},
  {NAME:"Odyssey of the Mind",DAY:"wednesday",MIN_AGE:3,MAX_AGE:5, TEACHER:"Gomes", ROOM:6,TYPE:"default", START_TIME:"11:30", END_TIME:"12:30"},
  {NAME:"Intro to Music Theory",DAY:"wednesday",MIN_AGE:10,MAX_AGE:19, TEACHER:"Barrera", ROOM:1,TYPE:"default", START_TIME:"12", END_TIME:"1"},
  {NAME:"Writing Fiction - Composition",DAY:"wednesday",MIN_AGE:14,MAX_AGE:18, TEACHER:"Lusteck", ROOM:5,TYPE:"default", START_TIME:"12", END_TIME:"1:30"},
  {NAME:"Contemporary Guitar 1",DAY:"wednesday",MIN_AGE:9,MAX_AGE:19, TEACHER:"L. Dircks", ROOM:8,TYPE:"default", START_TIME:"12", END_TIME:"1"},
  {NAME:"Leaps...Turns... Creating Choreography Int/Adv",DAY:"wednesday",MIN_AGE:11,MAX_AGE:19, TEACHER:"Fisher", ROOM:9,TYPE:"default", START_TIME:"12", END_TIME:"1"},
  {NAME:"Fitness Fun with Friends!",DAY:"wednesday",MIN_AGE:6,MAX_AGE:10, TEACHER:"Jenkins", ROOM:10,TYPE:"default", START_TIME:"12:30", END_TIME:"1:15"},
  {NAME:"Guitar Fundamentals",DAY:"wednesday",MIN_AGE:10,MAX_AGE:19, TEACHER:"Barrera", ROOM:1,TYPE:"default", START_TIME:"1", END_TIME:"2"},
  {NAME:"Butterfly Garden Preschool",DAY:"wednesday",MIN_AGE:4,MAX_AGE:5, TEACHER:"Gomes", ROOM:6,TYPE:"default", START_TIME:"1", END_TIME:"3"},
  {NAME:"Tap 5",DAY:"wednesday",MIN_AGE:10,MAX_AGE:19, TEACHER:"Fisher", ROOM:9,TYPE:"default", START_TIME:"1", END_TIME:"2"},
  {NAME:"Literature Alive ",DAY:"wednesday",MIN_AGE:6,MAX_AGE:10, TEACHER:"Jenkins ", ROOM:5,TYPE:"default", START_TIME:"1:45", END_TIME:"2:45"},
  {NAME:"Contemporary Guitar 2",DAY:"wednesday",MIN_AGE:9,MAX_AGE:19, TEACHER:"L. Dircks", ROOM:8,TYPE:"default", START_TIME:"2", END_TIME:"3"},
  {NAME:"Computer Science Discoveries 2",DAY:"wednesday",MIN_AGE:11,MAX_AGE:16, TEACHER:"Elkins", ROOM:2,TYPE:"default", START_TIME:"2", END_TIME:"4"},
  {NAME:"Chorale(or Men's/ Women's Chorus)",DAY:"wednesday",MIN_AGE:10,MAX_AGE:19, TEACHER:"Barrera", ROOM:3,TYPE:"default", START_TIME:"2", END_TIME:"4"},
  {NAME:"Praise / Contemporary III",DAY:"wednesday",MIN_AGE:9,MAX_AGE:19, TEACHER:"Harnsburger", ROOM:9,TYPE:"default", START_TIME:"2", END_TIME:"3"},
  {NAME:"Team Policy Debate",DAY:"wednesday",MIN_AGE:13,MAX_AGE:18, TEACHER:"Eschen", ROOM:8,TYPE:"default", START_TIME:"3", END_TIME:"4:30"},
  {NAME:"Calculus",DAY:"wednesday",MIN_AGE:14,MAX_AGE:18, TEACHER:"Tucker", ROOM:4,TYPE:"default", START_TIME:"3", END_TIME:"5"},
  {NAME:"Elementary Thinking & Problem Solving",DAY:"wednesday",MIN_AGE:6,MAX_AGE:10, TEACHER:"Jenkins", ROOM:5,TYPE:"default", START_TIME:"3", END_TIME:"4"},
  {NAME:"Tap 1",DAY:"wednesday",MIN_AGE:6,MAX_AGE:10, TEACHER:"B. Giordano", ROOM:9,TYPE:"default", START_TIME:"3", END_TIME:"4"},
  {NAME:"Proverbs: Applying God's Wisdom",DAY:"thursday",MIN_AGE:14,MAX_AGE:18, TEACHER:"Lusteck", ROOM:4,TYPE:"default", START_TIME:"9", END_TIME:"10"},
  {NAME:"Middle School Spanish",DAY:"thursday",MIN_AGE:10,MAX_AGE:13, TEACHER:"Zapata", ROOM:5,TYPE:"default", START_TIME:"9", END_TIME:"10"},
  {NAME:"Adventure Friends",DAY:"thursday",MIN_AGE:4,MAX_AGE:6, TEACHER:"Giordano", ROOM:6,TYPE:"default", START_TIME:"9", END_TIME:"10"},
  {NAME:"Tap 2/3",DAY:"thursday",MIN_AGE:8,MAX_AGE:19, TEACHER:"Fisher", ROOM:9,TYPE:"default", START_TIME:"9", END_TIME:"10"},
  {NAME:"Arizona History through Artistry",DAY:"thursday",MIN_AGE:8,MAX_AGE:11, TEACHER:"Sewell", ROOM:1,TYPE:"default", START_TIME:"10", END_TIME:"10:50"},
  {NAME:"Rhythmic Gymnastics 1",DAY:"thursday",MIN_AGE:8,MAX_AGE:19, TEACHER:"Fisher", ROOM:9,TYPE:"default", START_TIME:"10", END_TIME:"11"},
  {NAME:"History of the United States",DAY:"thursday",MIN_AGE:14,MAX_AGE:18, TEACHER:"Lusteck", ROOM:4,TYPE:"default", START_TIME:"10:15", END_TIME:"11:45"},
  {NAME:"Life Science",DAY:"thursday",MIN_AGE:4,MAX_AGE:6, TEACHER:"Giordano", ROOM:6,TYPE:"default", START_TIME:"10:15", END_TIME:"11:15"},
  {NAME:"Jazz Guitar",DAY:"thursday",MIN_AGE:10,MAX_AGE:19, TEACHER:"L. Dircks", ROOM:3,TYPE:"default", START_TIME:"10:30", END_TIME:"11:30"},
  {NAME:"MS Writing",DAY:"thursday",MIN_AGE:11,MAX_AGE:13, TEACHER:"Sewell", ROOM:1,TYPE:"default", START_TIME:"11", END_TIME:"12"},
  {NAME:"ASL Elementary",DAY:"thursday",MIN_AGE:6,MAX_AGE:10, TEACHER:"Anderegg", ROOM:5,TYPE:"default", START_TIME:"11", END_TIME:"12"},
  {NAME:"Ballet I/II",DAY:"thursday",MIN_AGE:12,MAX_AGE:19, TEACHER:"Harnsberger", ROOM:9,TYPE:"default", START_TIME:"11", END_TIME:"12:30"},
  {NAME:"Life Science",DAY:"thursday",MIN_AGE:8,MAX_AGE:12, TEACHER:"Giordano", ROOM:6,TYPE:"default", START_TIME:"11:30", END_TIME:"1"},
  {NAME:"MS Literature: Analysis, Writing, & Language Mechanics",DAY:"thursday",MIN_AGE:12,MAX_AGE:14, TEACHER:"Lusteck", ROOM:4,TYPE:"default", START_TIME:"12", END_TIME:"1:30"},
  {NAME:"Spanish I",DAY:"thursday",MIN_AGE:14,MAX_AGE:18, TEACHER:"Allwin", ROOM:5,TYPE:"default", START_TIME:"12", END_TIME:"1:30"},
  {NAME:"Art a la Carte",DAY:"thursday",MIN_AGE:7,MAX_AGE:9, TEACHER:"Sewell", ROOM:1,TYPE:"default", START_TIME:"12:15", END_TIME:"1:05"},
  {NAME:"Jazz Funk I/II",DAY:"thursday",MIN_AGE:8,MAX_AGE:19, TEACHER:" Harnsberger", ROOM:9,TYPE:"default", START_TIME:"1", END_TIME:"2"},
  {NAME:"Life Science",DAY:"thursday",MIN_AGE:6,MAX_AGE:8, TEACHER:"Giordano", ROOM:6,TYPE:"default", START_TIME:"1:15", END_TIME:"2:15"},
  {NAME:"Spanish 2",DAY:"thursday",MIN_AGE:14,MAX_AGE:18, TEACHER:"Allwin", ROOM:5,TYPE:"default", START_TIME:"1:30", END_TIME:"3"},
  {NAME:"Humanities",DAY:"thursday",MIN_AGE:14,MAX_AGE:18, TEACHER:"Lusteck", ROOM:4,TYPE:"default", START_TIME:"1:45", END_TIME:"3:15"},
  {NAME:"Advanced Acro",DAY:"thursday",MIN_AGE:7,MAX_AGE:19, TEACHER:" Harnsberger ", ROOM:9,TYPE:"default", START_TIME:"2", END_TIME:"3"},
  {NAME:"Intro to Photography ",DAY:"thursday",MIN_AGE:12,MAX_AGE:19, TEACHER:"Cooke ", ROOM:2,TYPE:"default", START_TIME:"2:30", END_TIME:"4"},
  {NAME:"Advanced Martial Arts",DAY:"thursday",MIN_AGE:-1,MAX_AGE:-1, TEACHER:"Fairweather", ROOM:8,TYPE:"default", START_TIME:"3", END_TIME:"4:30"},
  {NAME:"PBT",DAY:"thursday",MIN_AGE:99,MAX_AGE:19, TEACHER:"Harnsberger", ROOM:9,TYPE:"default", START_TIME:"3", END_TIME:"3:45"},
  {NAME:"Ballet Folklorico Beginning",DAY:"thursday",MIN_AGE:5,MAX_AGE:10, TEACHER:" Zapata", ROOM:9,TYPE:"default", START_TIME:"3:45", END_TIME:"4:45"},
  {NAME:"Ballet III ",DAY:"thursday",MIN_AGE:12,MAX_AGE:19, TEACHER:"Harnsberger", ROOM:9,TYPE:"default", START_TIME:"4:45", END_TIME:"6:15"}
];
